# Generated by Django 5.1.5 on 2025-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="machines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Machine_name", models.CharField(max_length=250)),
                ("Description", models.TextField()),
                ("Price", models.IntegerField()),
            ],
        ),
    ]
