# Generated by Django 5.1.5 on 2025-03-14 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_machines_image_machines_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machines",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 14, 20, 8, 51, 256576)
            ),
        ),
    ]
