# Generated by Django 5.1.5 on 2025-03-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_machines_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machines",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="machine_images/"),
        ),
        migrations.AlterField(
            model_name="machines",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
