# Generated by Django 5.1.5 on 2025-03-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_machines_image_alter_machines_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="machine_images/")),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.machines",
                    ),
                ),
            ],
        ),
    ]
