# Generated by Django 5.1.5 on 2025-03-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_product_productimages"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("phone", models.CharField(max_length=122)),
                ("email", models.CharField(max_length=122)),
                ("city", models.CharField(max_length=122)),
                ("porpose", models.CharField(max_length=122)),
                ("product_name", models.CharField(max_length=122)),
                ("product_price", models.IntegerField()),
            ],
        ),
    ]
